name: UMU Zipapp Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: Update APT Cache
      run: apt update -y

    - name: Install build dependencies
      run: apt install -y python3-venv python3-all bash make scdoc python3-hatchling python3-installer python3-build

    - name: Configure
      run: ./configure.sh --user-install

    - name: Build
      run: make all

    - name: Move DEB files to upload artifact path
      run: mkdir -p results && cp -rvf builddir/umu-run results/

    - name: Create symlink for launchers
      run: cd results && ln -s umu-run umu_run.py && cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: Zipapp
        path: results/
